// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxujSbSfid62tQVvbM_oQ8ymiXddMbFw',
    appId: '1:421467397862:web:20ecf3414cad5915a4a527',
    messagingSenderId: '421467397862',
    projectId: 'skillswap-41001',
    authDomain: 'skillswap-41001.firebaseapp.com',
    storageBucket: 'skillswap-41001.firebasestorage.app',
    measurementId: 'G-05PHDEEBRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASqDKE4c0J4wsa1AQG-VsOqrD2VOrEEuw',
    appId: '1:421467397862:android:34324c00aebcb6efa4a527',
    messagingSenderId: '421467397862',
    projectId: 'skillswap-41001',
    storageBucket: 'skillswap-41001.firebasestorage.app',
  );
}
